[package]
name = "rudu"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
filesize = "0.2.0"
owo-colors = "4.2.3"
tabled = { version = "0.20.0", features = ["ansi"] }
walkdir = "2.5.0"
